// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    LockerButton: typeof import('./src/components/LockerButton.vue')['default']
    LockerSearchLayout: typeof import('./src/components/LockerSearchLayout.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ViewLayout: typeof import('./src/components/ViewLayout.vue')['default']
  }
}

export {}
